GET http://localhost:3000/blog?page=1&search=react



###



POST http://localhost:3000/blog
Content-Type: application/json


{
    "topic":"javascript",
    "descripton":"javascript is a programming language",
    "posted_at":27-12-2020,
    "posted_by":"balajirock"


}